use_frameworks!

platform :ios, '10.0'

target 'AZLExtend_Example' do
  pod 'AZLExtend', :path => '../'

  target 'AZLExtend_Tests' do
    inherit! :search_paths

    
  end
end

target 'AZLExtendExampleSwift' do
  pod 'AZLExtendSwift', :path => '../'
end
