use_frameworks!

platform :ios, '10.0'

target 'AZLExtend_Example' do
  pod 'AZLExtend', :path => '../'

  target 'AZLExtend_Tests' do
    inherit! :search_paths

    
  end
end

target 'AZLExtendExampleSwift' do
  pod 'AZLExtendSwift', :path => '../'

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
end
end
  
  target 'AZLExtendExampleSwiftTests' do
    inherit! :search_paths

    
  end
end
